name: Label PR
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            github.pulls.createReview({
              pull_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              event: 'COMMENT',
              body: 'Review your PR',
              labels: ['new-pr', 'needs-review']
            })
