name: Selenium Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium pytest

    - name: Run Selenium tests
      run: |
        # Tu wpisz komendę uruchamiającą twoje testy Selenium, np.:
        pytest

    - name: Notify stakeholders
      if: always()
      uses: peter-evans/commit-comment@v1
      with:
        body: |
          Test results:
          ${{ steps.test.outputs.results }}
        token: ${{ secrets.GITHUB_TOKEN }}
