name: Slack Notification
on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: nazwa-twojego-kanalu
          SLACK_COLOR: '#36a64f'
          SLACK_MESSAGE: 'Nowa zmiana w repozytorium: ${{ github.event.head_commit.message }}'
          SLACK_USERNAME: GitHub Actions
          SLACK_TITLE: 'Aktualizacja Repozytorium'
